Repository FMIProjects/TalkFusion, pull requests merged in 2023-12, with the labels that each got.

#17 Added Channel Controller and View.
  TalkFusion/TalkFusion/Controllers/CategoriesController.cs
  TalkFusion/TalkFusion/Controllers/ChannelsController.cs
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Models/Category.cs
  TalkFusion/TalkFusion/Models/Channel.cs
  TalkFusion/TalkFusion/Models/Comment.cs
  TalkFusion/TalkFusion/Models/Group.cs
  TalkFusion/TalkFusion/Views/Categories/Edit.cshtml
  TalkFusion/TalkFusion/Views/Categories/Index.cshtml
  TalkFusion/TalkFusion/Views/Categories/New.cshtml
  TalkFusion/TalkFusion/Views/Categories/Show.cshtml
  TalkFusion/TalkFusion/Views/Channels/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/New.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
  TalkFusion/TalkFusion/Views/Shared/_Layout.cshtml
  TalkFusion/TalkFusion/wwwroot/js/toggleform.js
Labels: CV

#18 Added Comment Controller and View.
  TalkFusion/TalkFusion/Controllers/CommentsController.cs
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Models/Comment.cs
  TalkFusion/TalkFusion/Program.cs
  TalkFusion/TalkFusion/Views/Comments/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
  TalkFusion/TalkFusion/wwwroot/js/toggleform.js
Labels: CV

#26 Added Categories UR.
  TalkFusion/TalkFusion/Controllers/CategoriesController.cs
  TalkFusion/TalkFusion/Views/Shared/_Layout.cshtml
Labels: Users and Roles

#28 Added Channels UR.
  TalkFusion/TalkFusion/Controllers/ChannelsController.cs
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Views/Groups/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/ModeratedGroups.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
  TalkFusion/TalkFusion/Views/Groups/UnjoinedGroups.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
Labels: Users and Roles

#30 Added ReadMe.
  .gitignore
  README.md
  Resources/Logo.png
Labels: project

#32 Added Users MVC.
  .gitignore
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Controllers/UsersController.cs
  TalkFusion/TalkFusion/Program.cs
  TalkFusion/TalkFusion/Views/Groups/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/ModeratedGroups.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
  TalkFusion/TalkFusion/Views/Groups/UnjoinedGroups.cshtml
  TalkFusion/TalkFusion/Views/Shared/_Layout.cshtml
  TalkFusion/TalkFusion/Views/Users/GroupUserIndex.cshtml
  TalkFusion/TalkFusion/Views/Users/Index.cshtml
  TalkFusion/TalkFusion/Views/Users/Show.cshtml
Labels: model, CV, Users and Roles

#34 Added Members List.
  README.md
  TalkFusion/TalkFusion/Controllers/UsersController.cs
  TalkFusion/TalkFusion/Program.cs
  TalkFusion/TalkFusion/Views/Users/GroupUserIndex.cshtml
Labels: CV, Users and Roles

#40 36 Added search bars.
  TalkFusion/TalkFusion/Controllers/CategoriesController.cs
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Controllers/UsersController.cs
  TalkFusion/TalkFusion/Views/Categories/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/ModeratedGroups.cshtml
  TalkFusion/TalkFusion/Views/Groups/UnjoinedGroups.cshtml
  TalkFusion/TalkFusion/Views/Users/GroupUserIndex.cshtml
  TalkFusion/TalkFusion/Views/Users/Index.cshtml
  TalkFusion/TalkFusion/Views/Users/JoinRequestIndex.cshtml
Labels: enhancement

#41 Added Pagination.
  README.md
  TalkFusion/TalkFusion/Controllers/CategoriesController.cs
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Controllers/UsersController.cs
  TalkFusion/TalkFusion/Views/Categories/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/ModeratedGroups.cshtml
  TalkFusion/TalkFusion/Views/Groups/UnjoinedGroups.cshtml
  TalkFusion/TalkFusion/Views/Users/GroupUserIndex.cshtml
  TalkFusion/TalkFusion/Views/Users/Index.cshtml
  TalkFusion/TalkFusion/Views/Users/JoinRequestIndex.cshtml
Labels: enhancement

#49 Added FE - Navbar/Footer.
  TalkFusion/TalkFusion/Controllers/GroupsController.cs
  TalkFusion/TalkFusion/Views/Shared/_Layout.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
  TalkFusion/TalkFusion/wwwroot/resources/Logo-Horizontal.png
Labels: FrontEnd

#50 Added FE - Register/Login/Account.
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/ConfirmEmail.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Login.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Login.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Logout.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Logout.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/ChangePassword.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/DownloadPersonalData.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/Email.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/Email.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/Index.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/Index.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/ManageNavPages.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/PersonalData.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/SetPassword.cshtml.cs
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/_ManageNav.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Manage/_ViewImports.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/Register.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml
  TalkFusion/TalkFusion/Areas/Identity/Pages/Account/RegisterConfirmation.cshtml.cs
  TalkFusion/TalkFusion/Views/Shared/_Layout.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
  TalkFusion/TalkFusion/wwwroot/favicon.ico
  TalkFusion/TalkFusion/wwwroot/resources/Logo-Horizontal-White.png
  TalkFusion/TalkFusion/wwwroot/resources/Logo-Horizontal.png
Labels: FrontEnd

#51 Added FE Home Page.
  README.md
  TalkFusion/TalkFusion/Controllers/HomeController.cs
  TalkFusion/TalkFusion/Views/Home/Index.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
  TalkFusion/TalkFusion/wwwroot/resources/hero.jpg
Labels: FrontEnd

#53 Added FE Categories.
  TalkFusion/TalkFusion/Controllers/HomeController.cs
  TalkFusion/TalkFusion/Views/Categories/Edit.cshtml
  TalkFusion/TalkFusion/Views/Categories/Index.cshtml
  TalkFusion/TalkFusion/Views/Categories/New.cshtml
  TalkFusion/TalkFusion/Views/Categories/Show.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
Labels: FrontEnd

#54 Added FE Groups.
  TalkFusion/TalkFusion/Views/Groups/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/Index.cshtml
  TalkFusion/TalkFusion/Views/Groups/ModeratedGroups.cshtml
  TalkFusion/TalkFusion/Views/Groups/New.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
  TalkFusion/TalkFusion/Views/Groups/UnjoinedGroups.cshtml
Labels: FrontEnd

#55 Finished Channels FE.
  TalkFusion/TalkFusion/Views/Channels/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
Labels: FrontEnd

#56 Added FE Comments.
  TalkFusion/TalkFusion/TalkFusion.csproj
  TalkFusion/TalkFusion/Views/Categories/Edit.cshtml
  TalkFusion/TalkFusion/Views/Categories/New.cshtml
  TalkFusion/TalkFusion/Views/Channels/Edit.cshtml
  TalkFusion/TalkFusion/Views/Comments/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/Edit.cshtml
  TalkFusion/TalkFusion/Views/Groups/New.cshtml
  TalkFusion/TalkFusion/Views/Groups/Show.cshtml
  TalkFusion/TalkFusion/wwwroot/css/site.css
Labels: FrontEnd

#57 Added FE Users. The End!
  TalkFusion/TalkFusion/Views/Users/GroupUserIndex.cshtml
  TalkFusion/TalkFusion/Views/Users/Index.cshtml
  TalkFusion/TalkFusion/Views/Users/JoinRequestIndex.cshtml
  TalkFusion/TalkFusion/Views/Users/Show.cshtml
Labels: FrontEnd
